/******************************************************************************
 *
 * Module:ULTRASONIC
 *
 * File Name:  ULTRASONIC.h
 *
 * Description: Header file for the ULTRASONIC driver
 *
 * Author:Doaa Said
 *
 *******************************************************************************/
#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "../MCAL/std_types.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
/* ultrasonic_trigger HW Port and Pin Id */
#define  ULTRASONIC_Trigger_PORT_ID                 PORTD_ID
#define  ULTRASONIC_Trigger_PIN_ID                  PIN7_ID


/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/
/*
 * Description :
 *  Function responsible for Initializing the ICU driver as required,Set up the ICU callback function,
 Set the direction for the trigger pin as output through
 the GPIO driver.
 */
void Ultrasonic_init(void);

/*
 * Description :
 *  Function responsible for Sending the trigger pulse to the ultrasonic sensor.
 */
void Ultrasonic_Trigger(void);

/*
 * Description :
 *  Function responsible for Sending the trigger pulse by using the Ultrasonic_Trigger function
 ,Start the measurement process via the ICU driver and return The measured distance in centimeters.
 */

uint16 Ultrasonic_readDistance(void);

/*
 * Description :
 *  This is the callback function called by the ICU driver
 , It calculates the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */

